#!/bin/bash
# Auto-generated execution script
# Plan: {{PLAN_NAME}}
# Generated: {{DATE}}
#
# Usage:
#   ./PLAN-{{DATE}}-{{SLUG}}.sh                    # Normal execution
#   ./PLAN-{{DATE}}-{{SLUG}}.sh "go to step 3"     # Skip to specific step
#   ./PLAN-{{DATE}}-{{SLUG}}.sh "skip validation"  # Custom instruction
#
# This script handles:
# - Git branching from base branch
# - MCP configuration (if needed)
# - Step-by-step execution via execution agent
# - Commits after each step (by execution agent)
# - PR creation when complete
# - Plan status update (local, not committed)

set -e  # Exit on error

# ============================================================================
# CONFIGURATION (Auto-generated by planning agent)
# ============================================================================

PLAN_FILE="PLAN-{{DATE}}-{{SLUG}}.md"
PLAN_NAME="{{PLAN_NAME}}"
FEATURE_NAME="{{SLUG}}"
BRANCH_NAME="{{BRANCH_NAME}}"
BASE_BRANCH="{{BASE_BRANCH}}"
MCP_REQUIRED="{{MCP_REQUIRED}}"  # "none" or "chrome-devtools nextjs"
TOTAL_STEPS={{TOTAL_STEPS}}
CUSTOM_INSTRUCTION="${1:-}"  # Optional: custom instruction for execution agent

# ============================================================================
# COLORS & LOGGING
# ============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}ℹ${NC} $1"; }
log_success() { echo -e "${GREEN}✓${NC} $1"; }
log_warning() { echo -e "${YELLOW}⚠${NC} $1"; }
log_error() { echo -e "${RED}✗${NC} $1"; }

# ============================================================================
# SETUP
# ============================================================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🚀 Executing Plan: $PLAN_NAME"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
log_info "Plan file: .claude/plans/active/$PLAN_FILE"
log_info "Feature: $FEATURE_NAME"
log_info "Branch: $BRANCH_NAME"
log_info "Steps: $TOTAL_STEPS"
log_info "MCPs required: $MCP_REQUIRED"
echo ""

# ============================================================================
# GIT SETUP
# ============================================================================

log_info "Setting up git branch..."

# Ensure we're starting from latest base branch
log_info "Fetching latest changes from origin/$BASE_BRANCH..."
git fetch origin $BASE_BRANCH:refs/remotes/origin/$BASE_BRANCH

# Create or rebase feature branch
if git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
  log_warning "Branch $BRANCH_NAME already exists, checking out and rebasing..."
  git checkout $BRANCH_NAME
  git rebase origin/$BASE_BRANCH
  log_success "Branch rebased from origin/$BASE_BRANCH"
else
  log_info "Creating new branch from origin/$BASE_BRANCH..."
  git branch $BRANCH_NAME origin/$BASE_BRANCH
  git checkout $BRANCH_NAME
  log_success "Branch created from origin/$BASE_BRANCH"
fi

echo ""

# ============================================================================
# MCP CONFIGURATION
# ============================================================================

if [ "$MCP_REQUIRED" != "none" ]; then
  echo ""
  log_warning "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  log_warning " MCP Configuration Required"
  log_warning "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "This plan requires the following MCP servers:"
  echo "  $MCP_REQUIRED"
  echo ""
  echo "To configure MCPs for this worktree:"
  echo "  1. Ensure .mcp.json exists in this worktree"
  echo "  2. Enable required servers: $MCP_REQUIRED"
  echo "  3. Restart Claude Code session"
  echo ""
  log_warning "Press Enter when MCPs are configured (or skip if not needed)..."
  read -r
fi

# ============================================================================
# EXECUTION
# ============================================================================

log_info "Executing plan via /exec command..."
echo ""
echo "The execution agent will handle:"
echo "  ✓ All $TOTAL_STEPS plan steps"
echo "  ✓ Commits after each step"
echo "  ✓ Quality gates (from hooks)"
echo "  ✓ PR creation"
echo "  ✓ Plan status update"
echo ""

# Single call to execution agent - handles everything
claude --dangerously-skip-permissions "/exec $PLAN_FILE${CUSTOM_INSTRUCTION:+ $CUSTOM_INSTRUCTION}"

# Check if execution succeeded
EXEC_EXIT_CODE=$?

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ $EXEC_EXIT_CODE -ne 0 ]; then
  echo "  ❌ Plan Execution Failed"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  log_error "Execution agent encountered an error"
  log_warning "Check error messages above for details"
  log_warning "Run rollback steps from plan if needed"
  echo ""
  exit 1
fi

echo "  🎉 Plan Execution Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ============================================================================
# COMPLETION
# ============================================================================

log_success "✅ Execution agent completed successfully:"
echo ""
echo "   ✓ $TOTAL_STEPS plan steps executed"
echo "   ✓ All commits created"
echo "   ✓ Quality gates verified"
echo "   ✓ PR created and pushed"
echo "   ✓ Plan status updated to 'completed'"
echo ""
log_info "Check execution output above for:"
echo "   - PR URL"
echo "   - Verification results"
echo "   - Commit hashes"
echo ""
echo ""
log_success "Ready for PR review and merge!"
echo ""
